name: Build and Update Beehiiv Feed

on:
  schedule:
    # 05:40 Australia/Brisbane daily == 19:40 UTC previous day
    - cron: "40 19 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-and-update
  cancel-in-progress: true

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Analyze (AI filter + rewrite)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RSS_DB_PATH: rss_items.db
          LOG_LEVEL: INFO
          SCAN_WINDOW_HRS: "24"
          ALWAYS_AI: "1"
          MIN_SCORE_FOR_AI: "4"       # bump to 5 if still too many items
          OAI_RPM: "25"
          OAI_MAX_RETRIES: "4"
          FEED_TIMEOUT: "15"
        run: |
          set -euxo pipefail
          python rss_analyzer.py

      - name: Write Beehiiv feed
        env:
          RSS_DB_PATH: rss_items.db
          OUT_PATH: beehiiv.xml
          NEWSLETTER_NAME: "Morning Briefing"
          BASE_URL: "https://mwhiteoak.github.io/morningBrief"
          SCAN_WINDOW_HRS: "24"
        run: |
          set -euxo pipefail
          python write_beehiiv_feed.py
          echo "Items in beehiiv.xml: $(grep -c '<item>' beehiiv.xml || true)"

      - name: Commit & push XML
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add beehiiv.xml
          git commit -m "Update Beehiiv feed" || echo "No changes"
          git pull --rebase --autostash || true
          git push
