name: Build and Update Feeds

on:
  # 05:40 Australia/Brisbane daily (UTC+10, no DST) = 19:40 UTC previous day
  schedule:
    - cron: "40 19 * * *"
  workflow_dispatch:

permissions:
  contents: write  # needed so the workflow can push the XMLs

concurrency:
  group: build-and-update
  cancel-in-progress: true

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: pip install -r requirements.txt

      # 1) Prepare DB + AI summaries in the SAME runner
      - name: Run RSS Analyzer (populate rss_items.db)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RSS_DB_PATH: rss_items.db
          ALWAYS_AI: "1"              
          MIN_SCORE_FOR_AI: "0"
          TZ_REGION: "Australia/Brisbane"
          LOG_LEVEL: "INFO"
          OAI_RPM: "25"
          OAI_MAX_RETRIES: "4"
          MAX_WORKERS: "8"
          FEED_TIMEOUT: "15"
        run: |
          set -euxo pipefail
          python rss_analyzer.py

      # 2) Write all Beehiiv-ready feeds (top/finance/property/startups/markets/macro etc.)
      - name: Write Beehiiv feeds
        env:
          RSS_DB_PATH: rss_items.db
          OUT_PREFIX: "beehiiv"
          NEWSLETTER_NAME: "Morning Briefing"
          BASE_URL: "https://mwhiteoak.github.io/morningBrief"
          SCAN_WINDOW_HRS: "36"
          MAX_ITEMS_PER_FEED: "80"
          REQUIRE_AI: "1"           
        run: |
          set -euxo pipefail
          python write_beehiiv_feeds.py

      # 3) Quick visibility in logs (won’t fail if a file is missing)
      - name: Show feed counts
        run: |
          for f in beehiiv_*.xml; do
            [ -f "$f" ] || continue
            echo ">> $f items: $(grep -c '<item>' "$f" || true)"
          done

      # 4) Commit/push just the feeds (no DB/logs)
      - name: Commit updated feeds
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add beehiiv_*.xml || true
          git commit -m "Update Beehiiv feeds" || echo "No XML changes to commit"

          # Rebase-pull just in case another push landed at the same time
          git pull --rebase --autostash || true
          git push
