name: prepare-summaries

on:
  workflow_dispatch:
  schedule:
    # Run daily earlier so publish has fresh DB
    - cron: "25 20 * * *"  # 05:25 AEST / 06:25 AEDT approximate (GitHub UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show head
        run: |
          echo "HEAD of rss_analyzer.py (first 35 lines):"
          head -n 35 rss_analyzer.py || true
          echo
          sha256sum rss_analyzer.py || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare DB (CRE-first AI rewrites + classify)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWSLETTER_NAME: "Morning Briefing"
          LOG_LEVEL: INFO
          OAI_RPM: 25
          OAI_MAX_RETRIES: 4
          MAX_WORKERS: 8
          FEED_TIMEOUT: 15
          MIN_SCORE_FOR_AI: 5
          RSS_DB_PATH: rss_items.db
          TZ_REGION: "Australia/Brisbane"
          SCAN_WINDOW_HRS: 36
        run: |
          set -euxo pipefail
          python rss_analyzer.py

      - name: Commit DB + logs (skip CI)
        run: |
          set -e
          git config user.name "rss-bot"
          git config user.email "rss-bot@users.noreply.github.com"
          git pull --rebase origin main || true
          git add -f rss_items.db rss_analyzer.log || true
          git commit -m "Prepare: update DB/logs [skip ci]" || echo "Nothing to commit"
          git push || echo "Nothing to push"

      - name: Upload db/logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-and-logs.zip
          path: |
            rss_items.db
            rss_analyzer.log
