name: Prepare Summaries (DB)

on:
  schedule:
    # 05:20 AEST (UTC+10) -> 19:20 UTC previous day
    - cron: "20 19 * * *"
  workflow_dispatch:

permissions:
  contents: write   # needed to push DB/logs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run analyser (populate DB)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWSLETTER_NAME: "Morning Briefing"
          LOG_LEVEL: "INFO"
          MAX_WORKERS: "8"
          FEED_TIMEOUT: "15"
          OAI_RPM: "25"
          OAI_MAX_RETRIES: "4"
          MIN_SCORE_FOR_AI: "5"
          SCAN_WINDOW_HRS: "36"
          MAX_PER_FEED: "20"
        run: |
          set -euxo pipefail
          python rss_analyzer.py
          tail -n 200 rss_analyzer.log || true

      - name: Commit DB + logs (force add, autostash rebase)
        run: |
          set -euxo pipefail
          git config user.name "rss-bot"
          git config user.email "rss-bot@users.noreply.github.com"

          # force-add even if ignored
          git add -f rss_items.db || true
          git add -f rss_analyzer.log || true

          # commit only if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "Prepare: update DB/logs [skip ci]"
            git pull --rebase --autostash || true
            git push
          else
            echo "Nothing to commit"
          fi
