name: prepare-summaries

on:
  schedule:
    # Runs daily before publish; AEST (Brisbane, UTC+10) 05:40 ≈ 19:40 UTC prior day
    - cron: "40 19 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show HEAD snippet
        run: |
          echo "HEAD of rss_analyzer.py (first 40 lines):"
          head -n 40 rss_analyzer.py || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare (fetch + AI summarise, fast)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RSS_DB_PATH: rss_items.db
          LOG_LEVEL: INFO
          OPENAI_MODEL: gpt-4o-mini
          OAI_RPM: "60"
          OAI_MAX_RETRIES: "3"
          OAI_TIMEOUT_SECS: "15"
          MAX_WORKERS: "12"
          FEED_TIMEOUT: "10"
          SCAN_WINDOW_HRS: "18"
          MIN_SCORE_FOR_AI: "7"
          MAX_AI_ITEMS: "28"
        run: |
          set -euxo pipefail
          python rss_analyzer.py
          echo "=== SUMMARY DONE ==="

      - name: Commit DB + logs (optional cache)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          git config user.name "rss-bot"
          git config user.email "rss-bot@users.noreply.github.com"
          git pull --rebase origin "${GITHUB_REF_NAME:-main}" || true
          git add -f rss_items.db || true
          git add -f rss_analyzer.log || true
          git commit -m "Prepare: update DB/logs [skip ci]" || true
          git push origin HEAD:${GITHUB_REF_NAME:-main} || true

      - uses: actions/upload-artifact@v4
        with:
          name: db-and-logs
          path: |
            rss_items.db
            rss_analyzer.log
