name: Prepare Summaries (05:30 AEST)
on:
  schedule:
    - cron: '30 19 * * *'   # 05:30 AEST daily (Brisbane = UTC+10)
  workflow_dispatch: {}
concurrency:
  group: prepare-summaries
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch & summarise (throttled)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWSLETTER_NAME: "Morning Briefing"
          OAI_RPM: "25"         # stay well under limits
          OAI_MAX_RETRIES: "4"
        run: |
          python rss_analyzer.py
      - name: Persist DB (cache packages)
        run: |
          git config user.name "rss-bot"
          git config user.email "rss-bot@example.com"
          git add rss_items.db rss_analyzer.log || true
          git commit -m "Cache AI packages" || echo "Nothing to commit"
          git push || true
