name: Publish Beehiiv Feeds

on:
  schedule:
    # 05:55 AEST (UTC+10) -> 19:55 UTC previous day
    - cron: "55 19 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build multi-feeds (AI-only, non-empty bodies)
        env:
          RSS_DB_PATH: rss_items.db
          OUT_PREFIX: beehiiv
          NEWSLETTER_NAME: "Morning Briefing"
          BASE_URL: "https://mwhiteoak.github.io/morningBrief"
          SCAN_WINDOW_HRS: "36"
          MAX_ITEMS_PER_FEED: "80"
        run: |
          set -euxo pipefail
          python write_beehiiv_feeds.py

      - name: Build macro feed (always emits)
        env:
          BASE_URL: "https://mwhiteoak.github.io/morningBrief"
          NEWSLETTER_NAME: "Morning Briefing"
          MACRO_OUT_PATH: "beehiiv_macro.xml"
          # Optionally set these via repo secrets / env:
          # ASX200: "—"
          # AUDUSD: "—"
          # AU10Y: "—"
          # RBA_CASH: "—"
          # RBA_NEXT_MOVE_PROB: "—"
          # MACRO_TAKE: "Risk-on morning; lenders bid; dev feasos ease a touch."
        run: |
          set -euxo pipefail
          python write_macro_xml.py

      - name: Commit feeds
        run: |
          set -euxo pipefail
          git config user.name "rss-bot"
          git config user.email "rss-bot@users.noreply.github.com"

          git add beehiiv_*.xml || true
          if ! git diff --cached --quiet; then
            git commit -m "Update daily Beehiiv feeds"
            git pull --rebase --autostash || true
            git push
          else
            echo "No feed changes"
          fi
